name: OIDC AWS Test

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::263839541315:role/demo-git-aws
          aws-region: us-east-1

      - name: Test AWS Access
        run: aws s3 ls
      - name: Upload file to S3
        run: |
             echo "Hello from GitHub OIDC" > file.txt
             aws s3 cp file.txt s3://demo-git-aws/